export interface GetPropertyModel {
  id: number,
  userId: string,
  county: string,
  cityName: string,
  district: string,
  street: string,
  streetNumber: number,
  photos: string,
  isForSale: boolean,
  type: string,
  propertySize: number,
  groundSize: number,
  description: string,
  numberOfRooms: number,
  numberOfHalfRooms: number,
  price: number,
  condition: string,
  heat: string,
  yearOfBuild: number,
  numberOfFloors: string,
  comfort: string,
  isHandicapped: boolean,
  isAirConditionered: boolean,
  parking: string,
  createdAt: string
}
